"""Weather API setup wizard."""

from __future__ import annotations

import os
from pathlib import Path
import requests
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table
from rich import box

from ..core.location import Location


def test_openweathermap_api(api_key: str, location: Location | None = None) -> bool:
    """Test an OpenWeatherMap API key.

    Args:
        api_key: The API key to test
        location: Location to test against. Defaults to Brussels.

    Returns:
        True if the key is valid and working
    """
    loc = location or Location.brussels()
    try:
        response = requests.get(
            "https://api.openweathermap.org/data/2.5/weather",
            params={
                "lat": loc.latitude,
                "lon": loc.longitude,
                "appid": api_key,
                "units": "metric"
            },
            timeout=5,
        )
        return response.status_code == 200
    except Exception:
        return False


def test_weatherapi_key(api_key: str, location: Location | None = None) -> bool:
    """Test a WeatherAPI.com API key.

    Args:
        api_key: The API key to test
        location: Location to test against. Defaults to Brussels.

    Returns:
        True if the key is valid and working
    """
    loc = location or Location.brussels()
    try:
        response = requests.get(
            "https://api.weatherapi.com/v1/current.json",
            params={
                "key": api_key,
                "q": f"{loc.latitude},{loc.longitude}"
            },
            timeout=5,
        )
        return response.status_code == 200
    except Exception:
        return False


def load_env_file(path: Path) -> dict[str, str]:
    """Load environment variables from a .env file.

    Args:
        path: Path to the .env file

    Returns:
        Dictionary of environment variable name to value
    """
    config = {}
    if path.exists():
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    key, value = line.split("=", 1)
                    config[key.strip()] = value.strip().strip("\"'")
    return config


def save_env_file(path: Path, config: dict[str, str]) -> None:
    """Save environment variables to a .env file.

    Args:
        path: Path to the .env file
        config: Dictionary of environment variable name to value
    """
    with open(path, "w") as f:
        f.write("# Weather API Configuration for Satellite Monitor\n")
        f.write("# Generated by satellite-monitor setup\n\n")

        for key, value in config.items():
            if value:
                f.write(f"{key}={value}\n")


def run_setup_wizard(env_path: Path | None = None) -> dict[str, str]:
    """Run interactive weather API setup wizard.

    Args:
        env_path: Path to .env file. Defaults to current directory.

    Returns:
        Dictionary of configured API keys
    """
    console = Console()
    env_file = env_path or Path(".env")

    console.clear()
    console.print(
        Panel.fit(
            "Weather API Setup for Satellite Monitor",
            style="bold cyan",
        )
    )

    console.print(
        "\nWeather data helps recommend the best satellites based on current"
    )
    console.print(
        "cloud cover and visibility conditions.\n"
    )

    # Show API options
    table = Table(title="Available Weather API Options", box=box.ROUNDED)
    table.add_column("Provider", style="bold")
    table.add_column("Free Tier", style="green")
    table.add_column("Calls/Day", style="yellow")
    table.add_column("Sign Up URL", style="blue")

    table.add_row(
        "OpenWeatherMap", "Yes", "1,000",
        "https://openweathermap.org/api"
    )
    table.add_row(
        "WeatherAPI", "Yes", "1M/month",
        "https://www.weatherapi.com/"
    )
    table.add_row(
        "None", "Yes", "Unlimited (simulated)",
        "No signup needed"
    )

    console.print(table)
    console.print()

    # Load existing configuration
    existing_config = load_env_file(env_file)

    # Setup OpenWeatherMap
    console.print("\n[bold cyan]1. OpenWeatherMap Setup[/bold cyan]")
    openweather_key = _configure_api_key(
        console=console,
        existing_config=existing_config,
        key_name="OPENWEATHER_API_KEY",
        provider_name="OpenWeatherMap",
        signup_url="https://openweathermap.org/api",
        test_func=test_openweathermap_api
    )

    # Setup WeatherAPI
    console.print("\n[bold cyan]2. WeatherAPI.com Setup[/bold cyan]")
    weatherapi_key = _configure_api_key(
        console=console,
        existing_config=existing_config,
        key_name="WEATHERAPI_KEY",
        provider_name="WeatherAPI",
        signup_url="https://www.weatherapi.com/",
        test_func=test_weatherapi_key
    )

    # Save configuration
    console.print("\n[bold cyan]3. Saving Configuration[/bold cyan]")

    config = {
        "OPENWEATHER_API_KEY": openweather_key,
        "WEATHERAPI_KEY": weatherapi_key,
    }

    # Preserve other existing keys
    for key, value in existing_config.items():
        if key not in config:
            config[key] = value

    save_env_file(env_file, config)
    console.print(f"   Configuration saved to {env_file.absolute()}")

    # Update environment for current session
    if openweather_key:
        os.environ["OPENWEATHER_API_KEY"] = openweather_key
    if weatherapi_key:
        os.environ["WEATHERAPI_KEY"] = weatherapi_key

    # Show completion message
    _show_completion_panel(console, openweather_key, weatherapi_key)

    return config


def _configure_api_key(
    console: Console,
    existing_config: dict[str, str],
    key_name: str,
    provider_name: str,
    signup_url: str,
    test_func
) -> str:
    """Configure a single API key interactively.

    Returns:
        The configured API key (may be empty string)
    """
    if key_name in existing_config and existing_config[key_name]:
        existing = existing_config[key_name]
        console.print(f"   Existing key found: {existing[:8]}...")
        if Confirm.ask("   Keep existing key?", default=True):
            return existing
        else:
            return Prompt.ask(
                "   Enter new API key (or Enter to skip)",
                default=""
            )
    else:
        console.print("   No existing key found")
        if Confirm.ask(f"   Would you like to add a {provider_name} API key?", default=False):
            console.print(f"   Sign up at: [link]{signup_url}[/link]")
            api_key = Prompt.ask("   Enter your API key")

            # Test the key
            console.print("   Testing API key...", end="")
            if test_func(api_key):
                console.print(" [green]Success![/green]")
                return api_key
            else:
                console.print(" [red]Failed[/red]")
                if Confirm.ask("   Continue anyway?", default=True):
                    return api_key
                return ""
        return ""


def _show_completion_panel(
    console: Console,
    openweather_key: str,
    weatherapi_key: str
) -> None:
    """Show the setup completion panel."""
    if openweather_key or weatherapi_key:
        message = (
            "[bold green]Setup Complete![/bold green]\n\n"
            "Weather APIs configured. The system will now:\n"
            "* Get real-time cloud cover data\n"
            "* Recommend optical satellites when clear\n"
            "* Suggest SAR satellites when cloudy\n"
            "* Provide cost-optimized recommendations\n\n"
            "Run [cyan]satellite-monitor check[/cyan] to test."
        )
    else:
        message = (
            "[bold yellow]Setup Complete (Simulated Mode)[/bold yellow]\n\n"
            "No API keys configured. The system will use simulated weather data.\n"
            "This is fine for testing and demos.\n\n"
            "Run [cyan]satellite-monitor setup[/cyan] anytime to add API keys."
        )

    console.print("\n")
    console.print(Panel(message, title="Setup Complete", border_style="green"))
